name: s3 deployment

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Node setup
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: npm install
        run: npm i
        
      - name: Setup
        env:
          space_id: ${{ secrets.SPACE_ID }}
          management_access_token: ${{ secrets.MANAGEMENT_ACCESS_TOKEN }}
          delivery_access_token: ${{ secrets.DELIVERY_ACCESS_TOKEN }}
        run: | 
          npm run setup
          $space_id
          $management_access_token
          $delivery_access_token
 
      
      - name: build
        run: npm run build
      
      - name: copy files to s3
        run: aws s3 sync ./public/ s3://ipinki-test-task

      - name: Invalidate cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E1WNUNZXGNJBRU \
            --paths "/*"
